version: '2'

services:
  backend:
    build: ./backend/
    ports:
     - "5000:5000"
    volumes:
     - .:/backend
  frontend:
    build: ./frontend/
    ports:
     - "3000:3000"
    volumes:
     - .:/frontend